name: reference-lib CI

on:
  pull_request:
    branches: ['main']
    paths: ['reference-lib/**', '.github/workflows/reference-lib.yml']

permissions:
  contents: read

defaults:
  run:
    working-directory: ./reference-lib
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run test
      - run: npm run build
